#
# Test script for wkr API test
#

@baseUrl=http://localhost:8000
@token={{login.response.body.$.data}}
@test_job_id=hello
@test_run_id=1

# # # # # # # # # # # # # # # # #
# Ping health check
# @name ping
#
GET {{baseUrl}}/ping


###

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}


###

# @name jobs
GET {{baseUrl}}/jobs
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name job_details
GET {{baseUrl}}/jobs/{{test_job_id}}
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name job_run_details
GET {{baseUrl}}/jobs/{{test_job_id}}/{{test_run_id}}
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name job_run_execute
POST {{baseUrl}}/job/{{test_job_id}}/run
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "arguments": [
        "--configuration:Release",
        "--outputPath:./build/"
    ]
}


###
