#
# Test script for wkr API test
#

@baseUrl=http://localhost:8000
@token={{login.response.body.$.data}}
@test_job_id={{get_all_jobs.response.body.$.data.0.id}}
@test_run_id=1

# # # # # # # # # # # # # # # # #
# Ping health check
# @name ping
#
GET {{baseUrl}}/ping


###

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "name": "admin",
    "password": "admin"
}


###

# @name create_job
POST {{baseUrl}}/jobs/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "New job {{$randomInt 1 120}}",
    "params": {
        "executable": "cmd.exe",
        "arguments": [
            "/c",
            "echo/Hello World."
        ]
    }
}


###


# @name get_all_jobs
GET {{baseUrl}}/jobs
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name get_job_details
GET {{baseUrl}}/jobs/{{test_job_id}}
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name get_job_execution_results
GET {{baseUrl}}/jobs/{{test_job_id}}/{{test_run_id}}
Content-Type: application/json
Authorization: Bearer {{token}}


###

# @name execute_job
GET {{baseUrl}}/jobs/{{test_job_id}}/run
Content-Type: application/json
Authorization: Bearer {{token}}


###


# @name delete_job
POST {{baseUrl}}/jobs/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": "{{get_all_jobs.response.body.$.data.0.id}}"
}